export interface AppTextsConfig {
  aboutLabel?: string
  acceptCta?: string
  accountDetailsText?: string
  addOnSeparator?: string
  addOptionButtonabel?: string
  addServiceButtonLabel?: string
  addonSectionTitle?: string
  addressLabel?: string
  availabilityOff?: string
  availabilityOn?: string
  bannerText?: string
  bestOfferLabel?: string
  bestWasher?: string
  businessPageNameHint?: string
  businessTypeLabel?: string
  callClientCta?: string
  cancelCta?: string
  categorySectionTitle?: string
  completeCta?: string
  completeDialogDescription?: string
  completeDialogTitle?: string
  completeWashCta?: string
  compteEtDonneesLabel?: string
  confirmButton?: string
  connectMessage?: string
  constructionDescription?: string
  constructionTitle?: string
  copyToCategoriesModalTitle?: string
  dailyLabels?: string[]
  deleteAccountLabel?: string
  descriptionHint?: string
  descriptionLabel?: string
  fallbackClientName?: string
  languageLabel?: string
  logoutLabel?: string
  modifyProfileButtonLabel?: string
  monthlyLabels?: string[]
  newOrdersSectionTitle?: string
  noAddonForCategory?: string
  noAddonsAvailable?: string
  noClientPhoneAvailable?: string
  noDescriptionProvided?: string
  noPackageForCategory?: string
  noPackagesAvailable?: string
  noReservation?: string
  notAvailable?: string
  orderClientAddress?: string
  orderClientPhone?: string
  orderDate?: string
  orderOptions?: string
  orderPackage?: string
  orderProgress?: string
  orderTotal?: string
  orderVehicle?: string
  packageSectionTitle?: string
  paymentLabel?: string
  photosLabel?: string
  photosSectionTitle?: string
  priceLabelProfil?: string
  priceSuffix?: string
  proAccountAppbarTtitle?: string
  proAccountTitle?: string
  profileNameLabel?: string
  profileNamePlaceholder?: string
  profileTitle?: string
  progressDone?: string
  progressInProgress?: string
  progressNotStarted?: string
  readMore?: string
  rejectCta?: string
  reservationAcceptedError?: string
  reservationAcceptedSuccess?: string
  reservationCompletedError?: string
  reservationCompletedSuccess?: string
  reservationCreating?: string
  reservationRejectedError?: string
  reservationRejectedSuccess?: string
  reservationSimulatedSuccess?: string
  reservationSimulationError?: string
  ressourcesText?: string
  revenuePeriodDaily?: string
  revenuePeriodMonthly?: string
  revenueTitle?: string
  revenueVsPreviousMonth?: string
  reviewsCount?: string
  saveProfileButton?: string
  servicesSectionTitle?: string
  shopPageTitle?: string
  simulateReservationCta?: string
  statAverageBasket?: string
  statAverageRating?: string
  statOrders?: string
  statProfileViews?: string
  statsSectionTitle?: string
  statusAccepted?: string
  statusCancelled?: string
  statusCompleted?: string
  statusInProgress?: string
  statusPending?: string
  statusRejected?: string
  utilizeGoWashLabel?: string
  vehicleCompactImagePlaceholder?: string
  vehicleImagePlaceholder?: string
  vehicleSuvImagePlaceholder?: string
  yourNameHolder?: string
  [key: string]: any
}

export interface AppPanelConfig {
  [key: string]: any
}

export interface AppConfigDocument {
  delaiAttente?: number
  panelconfig?: AppPanelConfig
  shopOfferBackgroundImageUrl?: string
  texts?: AppTextsConfig
}
